name: Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno install
      - run: deno fmt --check
      - run: deno lint
#      - run: deno test

  ecr-workflow:
    uses: ./.github/workflows/ecr-workflow.yaml
    secrets: inherit
    with:
      image_repository: ${{ secrets.AWS_ECR_REPOSITORY }}
