name: Pull Request

on:
  workflow_dispatch:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: terraform fmt check
        uses: dflook/terraform-fmt-check@v1
        with:
          path: infra

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: deno install
      - run: deno fmt --check
      - run: deno lint
  #      - run: deno test

  ecr-workflow:
    needs: lint-and-test
    uses: ./.github/workflows/ecr-workflow.yaml
    secrets: inherit
    with:
      image_repository: "deno-aws"

  infra-workflow:
    needs: ecr-workflow
    uses: ./.github/workflows/infra-workflow.yaml
    secrets: inherit
